config/routes.rb
Rails.application.routes.draw do
  resources :rewards
  resources :logs
  resources :users
  resources :tasks
  resources :tags
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "dashboards#index"
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :user
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :set_reward, only: %i[ show edit update destroy ]

  # GET /rewards or /rewards.json
  def index
    @rewards = Reward.all
  end

  # GET /rewards/1 or /rewards/1.json
  def show
  end

  # GET /rewards/new
  def new
    @reward = Reward.new
  end

  # GET /rewards/1/edit
  def edit
  end

  # POST /rewards or /rewards.json
  def create
    @reward = Reward.new(reward_params)

    respond_to do |format|
      if @reward.save
        format.html { redirect_to reward_url(@reward), notice: "Reward was successfully created." }
        format.json { render :show, status: :created, location: @reward }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rewards/1 or /rewards/1.json
  def update
    respond_to do |format|
      if @reward.update(reward_params)
        format.html { redirect_to reward_url(@reward), notice: "Reward was successfully updated." }
        format.json { render :show, status: :ok, location: @reward }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rewards/1 or /rewards/1.json
  def destroy
    @reward.destroy

    respond_to do |format|
      format.html { redirect_to rewards_url, notice: "Reward was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reward
      @reward = Reward.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reward_params
      params.require(:reward).permit(:user_id, :title, :cost, :order, :expire_at, :minutes, :uses)
    end
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= form_with(model: reward) do |form| %>
  <% if reward.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
        <% reward.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :cost, style: "display: block" %>
    <%= form.number_field :cost %>
  </div>

  <div>
    <%= form.label :order, style: "display: block" %>
    <%= form.number_field :order %>
  </div>

  <div>
    <%= form.label :expire_at, style: "display: block" %>
    <%= form.datetime_field :expire_at %>
  </div>

  <div>
    <%= form.label :minutes, style: "display: block" %>
    <%= form.number_field :minutes %>
  </div>

  <div>
    <%= form.label :uses, style: "display: block" %>
    <%= form.number_field :uses %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rewards/_reward.html.erb
<div id="<%= dom_id reward %>">
  <p>
    <strong>User:</strong>
    <%= reward.user_id %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= reward.title %>
  </p>

  <p>
    <strong>Cost:</strong>
    <%= reward.cost %>
  </p>

  <p>
    <strong>Order:</strong>
    <%= reward.order %>
  </p>

  <p>
    <strong>Expire at:</strong>
    <%= reward.expire_at %>
  </p>

  <p>
    <strong>Minutes:</strong>
    <%= reward.minutes %>
  </p>

  <p>
    <strong>Uses:</strong>
    <%= reward.uses %>
  </p>

</div>

app/views/rewards/edit.html.erb
<h1>Editing reward</h1>

<%= render "form", reward: @reward %>

<br>

<div>
  <%= link_to "Show this reward", @reward %> |
  <%= link_to "Back to rewards", rewards_path %>
</div>

app/views/rewards/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rewards</h1>

<div id="rewards">
  <% @rewards.each do |reward| %>
    <%= render reward %>
    <p>
      <%= link_to "Show this reward", reward %>
    </p>
  <% end %>
</div>

<%= link_to "New reward", new_reward_path %>

app/views/rewards/new.html.erb
<h1>New reward</h1>

<%= render "form", reward: @reward %>

<br>

<div>
  <%= link_to "Back to rewards", rewards_path %>
</div>

app/views/rewards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reward %>

<div>
  <%= link_to "Edit this reward", edit_reward_path(@reward) %> |
  <%= link_to "Back to rewards", rewards_path %>

  <%= button_to "Destroy this reward", @reward, method: :delete %>
</div>